# Deployment MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-rotten-mongodb
spec:
  selector:
    matchLabels:
      app: rotten-mongodb
  template:
    metadata:
      labels:
        app: rotten-mongodb
    spec:
      containers:
        - name: rotten-mongodb
          image: mongo:5.0.5
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongouser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopwd

---

# Service do MongoDB
apiVersion: v1
kind: Service
metadata:
  name: serv-rotten-mongodb
spec:
  selector:
    app: rotten-mongodb
  ports:
    - port: 27017
  type: ClusterIP

---

# Deployment Web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-rotten-web
spec:
  selector:
    matchLabels:
      app: rotten-web
  template:
    metadata:
      labels:
        app: rotten-web
    spec:
      containers:
        - name: rotten-web
          image: marciodma/rotten-potatoes-kubedev:v1
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_DB
              value: admin
            - name: MONGODB_HOST
              value: serv-rotten-mongodb
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: mongouser
            - name: MONGODB_PASSWORD
              value: mongopwd

---

# Service Web
apiVersion: v1
kind: Service
metadata:
  name: serv-rotten-web
spec:
  selector:
    app: rotten-web
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  type: LoadBalancer
